//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBHA_Hockey_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coach
    {
        public int ID { get; set; }
        public System.DateTime Added { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    }
}
