//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBHA_Hockey_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prestonjang_VBHA_HockeyAppEntities : DbContext
    {
        public prestonjang_VBHA_HockeyAppEntities()
            : base("name=prestonjang_VBHA_HockeyAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<coach> coaches { get; set; }
        public DbSet<team> teams { get; set; }
        public DbSet<player> players { get; set; }
    }
}
