//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBHA_Hockey_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int ID { get; set; }
        public System.DateTime Added { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public int Speed { get; set; }
        public int Shot { get; set; }
        public int Dexterity { get; set; }
        public int Tenacity { get; set; }
        public int HockeyIQ { get; set; }
        public int Attendance { get; set; }
        public string Birthday { get; set; }
        public int TeamID { get; set; }
    }
}
